#!/usr/bin/env bash
# Regenerate data/wordlist.txt from SCOWL.
#
# The output is committed, so this only runs when the list is being changed or
# refreshed. It exists so the provenance of a megabyte of embedded data is a
# script anyone can rerun rather than a blob someone once pasted in.
#
# WHY SCOWL, AND WHY THIS SLICE
#
# The backstop was /usr/share/dict/words — `web2`, Webster's Second
# International of 1934. It is a *headword* list: `begin` and `hold` but not
# `began` or `held`; `boxcar` and `boxberry` but not `box`. It also carries no
# frequency information, so `smal` drew `small`, `smalm`, and `smalt` as equals.
#
# SCOWL fixes both. Its size levels are themselves a frequency ranking — level
# 10 is roughly the 1000 most common words, and each level is rarer than the
# last — so one file supplies membership *and* rank.
#
# LICENSING: levels 10 through 70 only.
#
# This is not arbitrary. SCOWL's components have different terms, and the one
# with a real condition — UKACD, which requires its notice reproduced verbatim
# — enters at **level 80**. Everything at or below 70 comes from Moby (public
# domain), Brian Kelk's UK wordlist (public domain), 12Dicts and 5desk (public
# domain), and ENABLE (public domain), under Kevin Atkinson's MIT-like grant.
# Staying at 70 keeps this a copyright notice in a text file and nothing more.
#
# Level 80 is also where quality falls off for our purposes: it is where
# obscure and cryptic-crossword vocabulary arrives, which is exactly the
# material that produced bad suggestions in the first place.
set -euo pipefail

VERSION="${SCOWL_VERSION:-2020.12.07}"
MAX_LEVEL="${MAX_LEVEL:-60}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/data/wordlist.txt"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "fetching SCOWL $VERSION..."
curl -sSL -o "$WORK/scowl.tar.gz" \
    "https://downloads.sourceforge.net/wordlist/scowl-$VERSION.tar.gz"
tar xzf "$WORK/scowl.tar.gz" -C "$WORK"
SRC="$WORK/scowl-$VERSION/final"

# American English: the shared `english-*` lists plus the US spellings. British
# and Canadian variants are deliberately excluded — accepting both `colour` and
# `color` means never flagging either, and a checker that accepts everything is
# the failure mode this project is built to avoid.
{
    echo "# Generated by script/build-wordlist.sh from SCOWL $VERSION."
    echo "# Levels 10-$MAX_LEVEL. See that script for why this slice, and"
    echo "# data/COPYING.wordlist for the license. Do not edit by hand."
    for level in 10 20 35 40 50 55 60 70; do
        [ "$level" -le "$MAX_LEVEL" ] || continue
        # Words, contractions, and abbreviations — all things a person writes.
        # `*-upper` (proper names) is excluded: names are a separate axis here,
        # and folding them in would let a misspelling hide behind a surname.
        files=()
        for kind in words contractions abbreviations; do
            for variant in english american; do
                f="$SRC/$variant-$kind.$level"
                [ -f "$f" ] && files+=("$f")
            done
        done
        [ ${#files[@]} -gt 0 ] || continue
        echo "#$level"
        # SCOWL ships Latin-1; anything non-ASCII is an accented loanword that
        # the tokenizer would never hand us anyway.
        cat "${files[@]}" |
            iconv -f ISO-8859-1 -t UTF-8 |
            tr '[:upper:]' '[:lower:]' |
            grep -E "^[a-z']+$" |
            LC_ALL=C sort -u
    done
} >"$OUT.tmp"

# Later levels repeat nothing from earlier ones, but a word can appear in both
# the english-* and american-* list of the same level, and the per-level sort
# above cannot see across levels. Keep the FIRST (most common) level for each.
awk '
    /^#/ { if ($0 ~ /^#[0-9]+$/) level = $0; print; next }
    !seen[$0]++ { print }
' "$OUT.tmp" >"$OUT"
rm -f "$OUT.tmp"

words=$(grep -cv '^#' "$OUT")
echo "wrote $OUT: $words words, $(du -h "$OUT" | cut -f1)"
