#!/usr/bin/env python3
"""Turn merged Google Books bigram counts into data/cues.txt.

Split out from build-cues.sh so thresholds can be swept without re-fetching
39 GB. Called as:

    derive-cues.py <counts.tsv> <sets.txt> <wordlist.txt> <out> \
        <min_count> <ratio> <max_per_word>

A context word earns a cue when one member of a confusion set takes it and the
others essentially do not. What counts as "essentially" is the ratio, and it is
the only thing standing between this table and a checker that flags correct
English -- see build-cues.sh for how that went wrong once.
"""
import sys
from collections import defaultdict

counts_path, sets_path, wordlist_path, out_path = sys.argv[1:5]
MIN_COUNT, RATIO, MAX_PER_WORD = (int(x) for x in sys.argv[5:8])

sets = [line.split() for line in open(sets_path) if line.split()]
member_of = {w: s for s in sets for w in s}

# Only context words the bundled dictionary knows. Google Books carries a
# century of OCR errors, and a cue nobody can spell is a cue that never fires.
known = {
    line.strip()
    for line in open(wordlist_path)
    if line.strip() and not line.startswith("#")
}

# before[(confusable, context)] and after[(confusable, context)]
before, after = defaultdict(int), defaultdict(int)
for line in open(counts_path):
    gram, _, n = line.rstrip("\n").rpartition("\t")
    if not n.isdigit():
        continue
    a, _, b = gram.partition(" ")
    n = int(n)
    if b in member_of and a in known:
        before[(b, a)] += n
    if a in member_of and b in known:
        after[(a, b)] += n

def cues(table, position):
    # Group by (set, context) so the members can be compared against each other.
    by_context = defaultdict(dict)
    for (word, context), n in table.items():
        by_context[(id(member_of[word]), context)][word] = n
    out = []
    for (_, context), scores in by_context.items():
        members = member_of[next(iter(scores))]
        ranked = sorted(
            ((scores.get(m, 0), m) for m in members), reverse=True
        )
        (best, word), (runner, _) = ranked[0], ranked[1]
        if best < MIN_COUNT or best < RATIO * (runner + 1):
            continue
        out.append((word, position, context, best))
    return out

found = cues(before, "before") + cues(after, "after")

# Keep the strongest per word, so one prolific confusable cannot crowd out the
# rest of the table.
per_word = defaultdict(list)
for word, position, context, n in sorted(found, key=lambda r: -r[3]):
    if len(per_word[word]) < MAX_PER_WORD:
        per_word[word].append((position, context, n))

with open(out_path, "w") as fh:
    print("# Generated by script/build-cues.sh. Do not edit by hand.", file=fh)
    print("# Derived from Google Books Ngrams (CC BY 3.0), Google Inc.", file=fh)
    print(f"# min_count={MIN_COUNT} ratio={RATIO} per_word={MAX_PER_WORD}", file=fh)
    print("# <position>\\t<context word>\\t<the word it selects>", file=fh)
    for word in sorted(per_word):
        for position, context, _ in sorted(per_word[word]):
            print(f"{position}\t{context}\t{word}", file=fh)

total = sum(len(v) for v in per_word.values())
print(f"wrote {out_path}: {total} cues across {len(per_word)} words")
