//! The backstop dictionary — a floor rather than an authority.
//!
//! A generic dictionary is wrong about your vocabulary in one direction only:
//! it doesn't know your jargon. It's still right about ordinary English, so we
//! keep it underneath the lexicon and let the lexicon override it.
//!
//! The list is **bundled**, not read from the system. It used to be
//! `/usr/share/dict/words`, which on macOS is `web2` — Webster's Second
//! International of 1934 — and that turned out to be wrong in three ways at
//! once. It is a *headword* list, holding `begin` and `hold` but not `began`
//! or `held`, and `boxcar` and `boxberry` but not `box`. It is ninety years
//! stale. And it carries no frequency information, so `smal` drew `small`,
//! `smalm`, and `smalt` as equally good corrections.
//!
//! SCOWL answers all three. Its size levels are a frequency ranking — level 10
//! is roughly the thousand most common words — so membership and rank come
//! from one file. Bundling it also removes the last thing this crate needed
//! from the host, which is why it now works the same on a machine that has no
//! word list installed at all.

use std::collections::HashMap;

/// The bundled list: `#<level>` section markers, then one lowercase word per
/// line. Generated by `script/build-wordlist.sh`; see it for provenance.
const WORDLIST: &str = include_str!("../data/wordlist.txt");

/// Words that are common enough to be worth knowing, and how common.
///
/// The value is the SCOWL level: 10 for the most frequent thousand, rising to
/// 70 for the rare tail. Lower is more common.
pub type Dictionary = HashMap<String, u8>;

/// Ignore words rarer than this. SCOWL's upper levels are where cryptic
/// crossword vocabulary lives, and a word list that accepts `smalt` is how a
/// checker offers it as a correction.
const MAX_LEVEL: u8 = 60;

/// Parse the bundled list.
pub fn load() -> Option<Dictionary> {
    let mut out = Dictionary::default();
    let mut level = MAX_LEVEL;
    for line in WORDLIST.lines() {
        if let Some(rest) = line.strip_prefix('#') {
            match rest.parse::<u8>() {
                Ok(n) => level = n,
                // A comment, not a section marker.
                Err(_) => continue,
            }
            continue;
        }
        if line.is_empty() || level > MAX_LEVEL {
            continue;
        }
        out.insert(line.to_string(), level);
    }
    (!out.is_empty()).then_some(out)
}

/// Build a dictionary from a bare word list, at an unremarkable level.
///
/// For fixtures. Level 40 rather than 10 on purpose: a hand-written test list
/// carries no frequency information, and claiming every word in it is among
/// the thousand most common would quietly decide ranking tests that mean to be
/// about something else.
pub fn from_words<I: IntoIterator<Item = S>, S: AsRef<str>>(words: I) -> Dictionary {
    words
        .into_iter()
        .map(|w| (w.as_ref().to_string(), 40u8))
        .collect()
}

/// How common a word is, as a SCOWL level. `None` for words not in the list.
pub fn level(dict: &Dictionary, word: &str) -> Option<u8> {
    dict.get(word).copied()
}

/// Is `word` known, allowing for regular inflection? Checks the surface form
/// first, then peels common suffixes back to a base form.
pub fn contains(words: &Dictionary, word: &str) -> bool {
    if words.contains_key(word) {
        return true;
    }
    base_forms(word).iter().any(|b| words.contains_key(b))
}

/// Candidate base forms for an inflected word. Over-generates on purpose —
/// a spurious base that happens to be a real word means we accept a word we
/// might have flagged, which is the direction we want to err in.
fn base_forms(word: &str) -> Vec<String> {
    let mut out = Vec::new();
    let mut push = |s: String| {
        if s.chars().count() >= 2 {
            out.push(s);
        }
    };

    // Contractions. The apostrophe isn't the morpheme boundary in the `n't`
    // family — `don't` splits to `don`, not `do` — so that case comes first.
    if let Some(stem) = word.strip_suffix("n't") {
        push(stem.to_string());
    }
    if let Some((head, _)) = word.split_once('\'') {
        push(head.to_string());
    }

    for suffix in ["s", "es", "ed", "ing", "ly", "er", "est", "ers", "ings"] {
        let Some(stem) = word.strip_suffix(suffix) else {
            continue;
        };
        if stem.is_empty() {
            continue;
        }
        push(stem.to_string());
        // `shipped` → `ship`, `running` → `run`: undo consonant doubling.
        let mut chars = stem.chars().rev();
        if let (Some(a), Some(b)) = (chars.next(), chars.next())
            && a == b
            && !"aeiou".contains(a)
        {
            push(stem[..stem.len() - a.len_utf8()].to_string());
        }
        // `shipping` → `ship` via the `e` that was dropped: `focusing` → `focuse`
        // is nonsense, but `focus` + `e` covers `larger` → `large`.
        push(format!("{stem}e"));
        // `carries` → `carry`, `happily` → `happy`.
        if let Some(without_i) = stem.strip_suffix('i') {
            push(format!("{without_i}y"));
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dict(words: &[&str]) -> Dictionary {
        from_words(words)
    }

    #[test]
    fn finds_exact_words() {
        assert!(contains(&dict(&["ship"]), "ship"));
        assert!(!contains(&dict(&["ship"]), "zzzz"));
    }

    #[test]
    fn folds_regular_inflections_back_to_the_base() {
        let d = dict(&["ship", "focus", "large", "carry"]);
        assert!(contains(&d, "ships"));
        assert!(contains(&d, "shipped"));
        assert!(contains(&d, "shipping"));
        assert!(contains(&d, "focused"));
        assert!(contains(&d, "larger"));
        assert!(contains(&d, "carries"));
    }

    #[test]
    fn handles_contractions() {
        assert!(contains(&dict(&["do"]), "don't"));
    }

    #[test]
    fn still_rejects_genuine_nonsense() {
        let d = dict(&["ship", "focus"]);
        assert!(!contains(&d, "shp"));
        assert!(!contains(&d, "flurb"));
    }
}
