//! The backstop dictionary — a floor rather than an authority.
//!
//! A generic dictionary is wrong about your vocabulary in one direction only:
//! it doesn't know your jargon. It's still right about ordinary English, so we
//! keep it underneath the lexicon and let the lexicon override it.
//!
//! The list is **bundled**, not read from the system. It used to be
//! `/usr/share/dict/words`, which on macOS is `web2` — Webster's Second
//! International of 1934 — and that turned out to be wrong in three ways at
//! once. It is a *headword* list, holding `begin` and `hold` but not `began`
//! or `held`, and `boxcar` and `boxberry` but not `box`. It is ninety years
//! stale. And it carries no frequency information, so `smal` drew `small`,
//! `smalm`, and `smalt` as equally good corrections.
//!
//! SCOWL answers all three. Its size levels are a frequency ranking — level 10
//! is roughly the thousand most common words — so membership and rank come
//! from one file. Bundling it also removes the last thing this crate needed
//! from the host, which is why it now works the same on a machine that has no
//! word list installed at all.

/// The bundled list: `#<level>` section markers, then one lowercase word per
/// line. Generated by `script/build-wordlist.sh`; see it for provenance.
const WORDLIST: &str = include_str!("../data/wordlist.txt");

/// Words that are common enough to be worth knowing, and how common.
///
/// The value is the SCOWL level: 10 for the most frequent thousand, rising to
/// 70 for the rare tail. Lower is more common.
/// A sorted slice of the embedded text, searched rather than hashed.
///
/// This was a `HashMap<String, u8>`, and building it cost about 8ms on every
/// invocation — most of the fixed cost of a check, for a lookup table that is
/// the same every time. Borrowing instead of allocating barely helped: the
/// cost was hashing 102,495 keys, not copying them.
///
/// A `Vec` is 36x cheaper to build, and the list is emitted globally sorted so
/// a lookup is a binary search. Loading is now a single pass with no hashing
/// at all.
pub type Dictionary = Vec<(&'static str, u8)>;

/// Ignore words rarer than this. SCOWL's upper levels are where cryptic
/// crossword vocabulary lives, and a word list that accepts `smalt` is how a
/// checker offers it as a correction.
const MAX_LEVEL: u8 = 60;

/// Parse the bundled list.
pub fn load() -> Option<Dictionary> {
    let out: Dictionary = WORDLIST
        .lines()
        .filter(|line| !line.starts_with('#') && !line.is_empty())
        .filter_map(|line| {
            let (word, level) = line.split_once('\t')?;
            let level: u8 = level.parse().ok()?;
            (level <= MAX_LEVEL).then_some((word, level))
        })
        .collect();
    debug_assert!(
        out.windows(2).all(|w| w[0].0 <= w[1].0),
        "the word list must be sorted; binary search depends on it"
    );
    (!out.is_empty()).then_some(out)
}

/// Build a dictionary from a bare word list, at an unremarkable level.
///
/// For fixtures. Level 40 rather than 10 on purpose: a hand-written test list
/// carries no frequency information, and claiming every word in it is among
/// the thousand most common would quietly decide ranking tests that mean to be
/// about something else.
pub fn from_words<I: IntoIterator<Item = &'static str>>(words: I) -> Dictionary {
    let mut out: Dictionary = words.into_iter().map(|w| (w, 40u8)).collect();
    out.sort_unstable();
    out
}

/// How common a word is, as a SCOWL level. `None` for words not in the list.
pub fn level(dict: &Dictionary, word: &str) -> Option<u8> {
    dict.binary_search_by(|(w, _)| (*w).cmp(word))
        .ok()
        .map(|i| dict[i].1)
}

/// Is `word` in the list?
///
/// This used to peel suffixes to a base form — `shipping` to `ship` — because
/// the old backstop carried headwords and few inflections. SCOWL carries the
/// inflections, so the stripper stopped paying for itself and started costing:
/// it over-generated on purpose, and every spurious base that happened to be a
/// real word accepted a typo. Removing it raised recall on the reference
/// corpus from 87.5% to 95.8% and left the false-positive set identical.
///
/// If a future word list lacks inflections, this is where morphology goes
/// back — but measure it against `vocab eval` first, because the intuition
/// that stemming can only help is what made the old version look free.
pub fn contains(words: &Dictionary, word: &str) -> bool {
    level(words, word).is_some()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dict(words: &[&'static str]) -> Dictionary {
        from_words(words.iter().copied())
    }

    #[test]
    fn finds_exact_words() {
        assert!(contains(&dict(&["ship"]), "ship"));
        assert!(!contains(&dict(&["ship"]), "zzzz"));
    }

    #[test]
    fn the_bundled_list_carries_inflections_itself() {
        // This is the guarantee that replaced suffix stripping, so it is worth
        // asserting rather than assuming: the irregular forms are the ones the
        // old backstop lacked and no stripper would have recovered.
        let d = load().expect("bundled list");
        for word in [
            "ships", "shipped", "shipping", "focused", "carries", "began", "held", "wrote", "box",
            "don't",
            // Not `debugger's`: possessives never reach here, because
            // `text::normalize` strips the `'s` before lookup.
            "debugger",
        ] {
            assert!(contains(&d, word), "{word} missing from the bundled list");
        }
    }

    #[test]
    fn the_bundled_list_omits_the_obscure_tail() {
        // `smalt` is level 70 and excluded on purpose — it is what made `smal`
        // ambiguous between three corrections.
        let d = load().expect("bundled list");
        assert!(!contains(&d, "smalt"));
        assert!(contains(&d, "small"));
    }

    #[test]
    fn still_rejects_genuine_nonsense() {
        let d = dict(&["ship", "focus"]);
        assert!(!contains(&d, "shp"));
        assert!(!contains(&d, "flurb"));
    }
}
